using UnityEngine;

public class MovingObstacle : MonoBehaviour
{
    [SerializeField] private Transform m_startWaypoint;
    [SerializeField] private Transform m_endWaypoint;
    [SerializeField] private float m_speed = 5;

    private Transform m_target;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        m_target = m_startWaypoint;
    }

    // Update is called once per frame
    void Update()
    {
        transform.position = Vector2.MoveTowards(transform.position, m_target.position, m_speed * Time.deltaTime);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("MovingObstacleStartWaypoint"))
        {
            ChangeTarget();
        }
        if (collision.CompareTag("MovingObstacleEndWaypoint"))
        {
            ChangeNewTarget();
        }
        if (collision.CompareTag("Player"))
        {
            Debug.Log("HitPlayerOWWW");
        }
    }

    void ChangeTarget()
    {
        m_target = m_endWaypoint;
    }

    void ChangeNewTarget()
    {
        m_target = m_startWaypoint;
    }

}
